/*
 * Copyright 2025 Kharl Ryan M. De Jesus
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//NODE MODULES
import { NextRequest, NextResponse } from 'next/server';

//CUSTOM MODULES
import { connectToDatabase } from '@/lib/mongoose';
import Class from '@/models/class';
import User from '@/models/user';

//MIDDLEWARE
import { authenticate } from '@/lib/middleware/authenticate';
import { authorize } from '@/lib/middleware/authorize';

/**
 * GET /api/teacher_page/class
 * Get all classes for a teacher
 */
export async function GET(request: NextRequest) {
  try {
    // Authenticate the user
    const authResult = await authenticate(request);
    if (authResult instanceof Response) {
      return authResult;
    }

    // Authorize teacher role
    const authzResult = await authorize(authResult.userId, ['teacher']);
    if (authzResult !== true) {
      return authzResult as Response;
    }

    await connectToDatabase();

    const { searchParams } = new URL(request.url);
    const isActive = searchParams.get('active'); // 'true', 'false'
    const limit = parseInt(searchParams.get('limit') || '50');
    const page = parseInt(searchParams.get('page') || '1');

    // Build query
    const query: any = { teacherId: authResult.userId.toString() };
    
    if (isActive !== null && isActive !== undefined) {
      query.isActive = isActive === 'true';
    }

    // Get classes with pagination
    const skip = (page - 1) * limit;
    const classes = await Class.find(query)
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(limit)
      .lean();

    // Get total count for pagination
    const total = await Class.countDocuments(query);

    return NextResponse.json({
      success: true,
      data: {
        classes,
        pagination: {
          current: page,
          total: Math.ceil(total / limit),
          count: classes.length,
          totalItems: total
        }
      }
    });

  } catch (error) {
    console.error('Error fetching classes:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

/**
 * POST /api/teacher_page/class
 * Create a new class
 */
export async function POST(request: NextRequest) {
  try {
    // Authenticate the user
    const authResult = await authenticate(request);
    if (authResult instanceof Response) {
      return authResult;
    }

    // Authorize teacher role
    const authzResult = await authorize(authResult.userId, ['teacher']);
    if (authzResult !== true) {
      return authzResult as Response;
    }

    await connectToDatabase();

    const body = await request.json();
    const {
      name,
      courseYear,
      subject,
      description,
      maxStudents,
      settings
    } = body;

    // Validate required fields
    if (!name || !courseYear || !subject) {
      return NextResponse.json(
        { error: 'Missing required fields: name, courseYear, subject' },
        { status: 400 }
      );
    }

    // Get teacher info for the class
    const teacher = await User.findById(authResult.userId).select('firstName lastName').lean();
    if (!teacher) {
      return NextResponse.json({ error: 'Teacher not found' }, { status: 404 });
    }

    // Create class
    const newClass = new Class({
      name,
      courseYear,
      subject,
      description,
      teacherId: authResult.userId.toString(),
      classCode: '', // Will be generated by the pre-save hook
      maxStudents,
      settings: settings || {}
    });

    // Generate join code
    newClass.generateclassCode();

    await newClass.save();

    return NextResponse.json({
      success: true,
      data: { class: newClass }
    }, { status: 201 });

  } catch (error) {
    console.error('Error creating class:', error);
    
    if (error instanceof Error) {
      // Handle validation errors
      if (error.name === 'ValidationError') {
        return NextResponse.json(
          { error: 'Validation error', details: error.message },
          { status: 400 }
        );
      }
      
      // Handle duplicate join code (very rare but possible)
      if (error.message.includes('duplicate key') && error.message.includes('classCode')) {
        return NextResponse.json(
          { error: 'Failed to generate unique join code. Please try again.' },
          { status: 500 }
        );
      }
    }
    
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}