"use client";

export default function TermsOfService() {
    return (
        <div className="prose prose-gray max-w-none">
            <div className="space-y-6 text-gray-700 leading-relaxed">
                <div>
                    <p className="text-sm text-gray-500 mb-4">Last updated: {new Date().toLocaleDateString()}</p>
                    <p className="text-lg">
                        Welcome to NoteWise! These Terms of Service ("Terms") govern your use of our AI-powered study platform and services.
                    </p>
                </div>

                <section>
                    <h3 className="text-xl font-semibold text-gray-900 mb-3">1. Acceptance of Terms</h3>
                    <p>
                        By creating an account or using NoteWise, you agree to be bound by these Terms and our Privacy Policy.
                        If you don't agree to these Terms, please don't use our service.
                    </p>
                </section>

                <section>
                    <h3 className="text-xl font-semibold text-gray-900 mb-3">2. Description of Service</h3>
                    <p>
                        NoteWise is an AI-powered educational platform that provides:
                    </p>
                    <ul className="list-disc pl-6 mt-2 space-y-1">
                        <li>AI-generated summaries of uploaded study materials</li>
                        <li>Interactive flashcard creation and review systems</li>
                        <li>File upload and processing capabilities for PDF, DOCX, and TXT formats</li>
                        <li>Personalized study tools and progress tracking</li>
                    </ul>
                </section>

                <section>
                    <h3 className="text-xl font-semibold text-gray-900 mb-3">3. User Accounts and Responsibilities</h3>
                    <div className="space-y-3">
                        <p><strong>Account Creation:</strong> You must provide accurate information when creating your account.</p>
                        <p><strong>Account Security:</strong> You're responsible for maintaining the security of your account credentials.</p>
                        <p><strong>Acceptable Use:</strong> You agree to use NoteWise only for legitimate educational purposes.</p>
                    </div>
                </section>

                <section>
                    <h3 className="text-xl font-semibold text-gray-900 mb-3">4. Content and Intellectual Property</h3>
                    <div className="space-y-3">
                        <p><strong>Your Content:</strong> You retain ownership of materials you upload to NoteWise.</p>
                        <p><strong>AI-Generated Content:</strong> Summaries and flashcards generated by our AI are provided for your educational use.</p>
                        <p><strong>Platform Content:</strong> NoteWise's software, design, and features are protected by intellectual property laws.</p>
                    </div>
                </section>

                <section>
                    <h3 className="text-xl font-semibold text-gray-900 mb-3">5. AI Services and Limitations</h3>
                    <div className="space-y-3">
                        <p><strong>AI Accuracy:</strong> While our AI strives for accuracy, generated summaries and flashcards should be reviewed and verified.</p>
                        <p><strong>Educational Purpose:</strong> Our AI tools are designed to assist learning, not replace critical thinking or original work.</p>
                        <p><strong>Content Processing:</strong> We use AI to analyze your uploaded materials to provide our services.</p>
                    </div>
                </section>

                <section>
                    <h3 className="text-xl font-semibold text-gray-900 mb-3">6. Privacy and Data Protection</h3>
                    <p>
                        Your privacy is important to us. Please review our Privacy Policy to understand how we collect,
                        use, and protect your information, including uploaded study materials and generated content.
                    </p>
                </section>

                <section>
                    <h3 className="text-xl font-semibold text-gray-900 mb-3">7. Prohibited Activities</h3>
                    <p>You agree not to:</p>
                    <ul className="list-disc pl-6 mt-2 space-y-1">
                        <li>Upload copyrighted materials without permission</li>
                        <li>Use the service for any illegal or unauthorized purpose</li>
                        <li>Attempt to reverse engineer or compromise our AI systems</li>
                        <li>Share your account credentials with others</li>
                        <li>Upload malicious files or content</li>
                    </ul>
                </section>

                <section>
                    <h3 className="text-xl font-semibold text-gray-900 mb-3">8. Service Availability</h3>
                    <p>
                        We strive to maintain high availability but cannot guarantee uninterrupted service.
                        We may temporarily suspend service for maintenance or updates.
                    </p>
                </section>

                <section>
                    <h3 className="text-xl font-semibold text-gray-900 mb-3">9. Limitation of Liability</h3>
                    <p>
                        NoteWise is provided "as is" for educational purposes. We're not liable for any academic
                        outcomes or decisions made based on AI-generated content. Always verify important information independently.
                    </p>
                </section>

                <section>
                    <h3 className="text-xl font-semibold text-gray-900 mb-3">10. Account Termination</h3>
                    <p>
                        You may delete your account at any time. We may suspend or terminate accounts that violate these Terms.
                        Upon termination, your access to the service will cease, but these Terms will continue to apply.
                    </p>
                </section>

                <section>
                    <h3 className="text-xl font-semibold text-gray-900 mb-3">11. Changes to Terms</h3>
                    <p>
                        We may update these Terms periodically. We'll notify users of significant changes via email or
                        platform notifications. Continued use after changes constitutes acceptance of new Terms.
                    </p>
                </section>

                <section>
                    <h3 className="text-xl font-semibold text-gray-900 mb-3">12. Contact Information</h3>
                    <p>
                        If you have questions about these Terms, please contact us at:
                    </p>
                    <div className="bg-gray-50 p-4 rounded-lg mt-2">
                        <p><strong>Email:</strong> legal@notewise.com</p>
                        <p><strong>Support:</strong> support@notewise.com</p>
                    </div>
                </section>

                <div className="border-t pt-6 mt-8">
                    <p className="text-sm text-gray-500">
                        By using NoteWise, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
                    </p>
                </div>
            </div>
        </div>
    );
}